export const applications = [
    {
        id: 'garasibmw-portal',
        name: 'GarasiBMW Portal',
        category: 'Budgeting & Finance',
        owner: 'Raka Adi',
        status: 'Active',
        updated: '20 Jul 2026',
        description: 'Sistem manajemen bengkel BMW yang menangani antrian servis, transaksi, dan suku cadang secara terpusat.',
        version: 'v2.4.1',
        url: 'smbgarasibmw.my.id',
        uptime: '99.7%',
        server: 'srv-jkt-03 (Ubuntu 22.04)',
        database: 'MySQL 8.0',
        sla: '99.5% uptime guaranteed',
        documentation: 'docs.smbgarasibmw.my.id',
        supportContact: 'support@smbgarasibmw.my.id',
    },
    {
        id: 'hris-telkomsel',
        name: 'HRIS Telkomsel',
        category: 'Engineering & Deployment',
        owner: 'Siti Rahma',
        status: 'Active',
        updated: '18 Jul 2026',
        description: 'Platform manajemen sumber daya manusia untuk pengelolaan data karyawan, absensi, dan payroll.',
        version: 'v5.0.2',
        url: 'hris.telkomsel.internal',
        uptime: '99.9%',
        server: 'srv-jkt-01 (Ubuntu 22.04)',
        database: 'PostgreSQL 15',
        sla: '99.9% uptime guaranteed',
        documentation: 'docs.hris.telkomsel.internal',
        supportContact: 'hris-support@telkomsel.internal',
    },
    {
        id: 'app-catalog-sso',
        name: 'App Catalog SSO',
        category: 'Operation',
        owner: 'Dimas Prayoga',
        status: 'Active',
        updated: '22 Jul 2026',
        description: 'Portal single sign-on terpusat untuk mengakses seluruh aplikasi internal perusahaan.',
        version: 'v1.2.0',
        url: 'appcatalog.internal',
        uptime: '99.95%',
        server: 'srv-jkt-02 (Ubuntu 22.04)',
        database: 'PostgreSQL 15',
        sla: '99.9% uptime guaranteed',
        documentation: 'docs.appcatalog.internal',
        supportContact: 'sso-support@telkomsel.internal',
    },
    {
        id: 'inventory-system',
        name: 'Inventory System',
        category: 'Others',
        owner: 'Fajar Nugroho',
        status: 'Inactive',
        updated: '10 Jun 2026',
        description: 'Sistem pengelolaan stok dan gudang, saat ini dinonaktifkan menunggu migrasi ke versi baru.',
        version: 'v1.8.4',
        url: 'inventory.internal',
        uptime: '0%',
        server: 'srv-jkt-05 (Ubuntu 20.04)',
        database: 'MySQL 5.7',
        sla: 'Tidak berlaku (nonaktif)',
        documentation: 'docs.inventory.internal',
        supportContact: 'inventory-support@telkomsel.internal',
    },
    {
        id: 'payroll-gateway',
        name: 'Payroll Gateway',
        category: 'Security',
        owner: 'Siti Rahma',
        status: 'Active',
        updated: '19 Jul 2026',
        description: 'Gateway integrasi penggajian yang menghubungkan HRIS dengan sistem perbankan mitra.',
        version: 'v2.0.1',
        url: 'payroll.internal',
        uptime: '99.6%',
        server: 'srv-jkt-04 (Ubuntu 22.04)',
        database: 'PostgreSQL 14',
        sla: '99.5% uptime guaranteed',
        documentation: 'docs.payroll.internal',
        supportContact: 'payroll-support@telkomsel.internal',
    },
    {
        id: 'security-scanner',
        name: 'Security Scanner',
        category: 'Security',
        owner: 'Dimas Prayoga',
        status: 'Active',
        updated: '21 Jul 2026',
        description: 'Alat pemindaian kerentanan otomatis untuk seluruh aplikasi yang terdaftar di catalog.',
        version: 'v4.3.0',
        url: 'secscan.internal',
        uptime: '99.9%',
        server: 'srv-jkt-06 (Ubuntu 22.04)',
        database: 'MongoDB 6.0',
        sla: '99.9% uptime guaranteed',
        documentation: 'docs.secscan.internal',
        supportContact: 'security-team@telkomsel.internal',
    },
    {
        id: 'budget-planning-tool',
        name: 'Budget Planning Tool',
        category: 'Budgeting & Finance',
        owner: 'Wulan Sari',
        status: 'Active',
        updated: '17 Jul 2026',
        description: 'Alat perencanaan anggaran tahunan untuk seluruh divisi, terintegrasi dengan laporan keuangan.',
        version: 'v1.5.0',
        url: 'budget.internal',
        uptime: '99.4%',
        server: 'srv-jkt-03 (Ubuntu 22.04)',
        database: 'MySQL 8.0',
        sla: '99.0% uptime guaranteed',
        documentation: 'docs.budget.internal',
        supportContact: 'finance-support@telkomsel.internal',
    },
    {
        id: 'expense-tracker',
        name: 'Expense Tracker',
        category: 'Budgeting & Finance',
        owner: 'Wulan Sari',
        status: 'Maintenance',
        updated: '14 Jul 2026',
        description: 'Pelacakan pengeluaran operasional harian, sedang dalam perbaikan modul laporan bulanan.',
        version: 'v2.1.3',
        url: 'expense.internal',
        uptime: '96.8%',
        server: 'srv-jkt-03 (Ubuntu 22.04)',
        database: 'MySQL 8.0',
        sla: '99.0% uptime guaranteed',
        documentation: 'docs.expense.internal',
        supportContact: 'finance-support@telkomsel.internal',
    },
    {
        id: 'ci-cd-pipeline-manager',
        name: 'CI/CD Pipeline Manager',
        category: 'Engineering & Deployment',
        owner: 'Raka Adi',
        status: 'Active',
        updated: '23 Jul 2026',
        description: 'Dashboard pemantauan pipeline GitHub Actions untuk seluruh proyek engineering internal.',
        version: 'v3.0.0',
        url: 'cicd.internal',
        uptime: '99.6%',
        server: 'srv-jkt-07 (Ubuntu 22.04)',
        database: 'PostgreSQL 15',
        sla: '99.5% uptime guaranteed',
        documentation: 'docs.cicd.internal',
        supportContact: 'devops-team@telkomsel.internal',
    },
    {
        id: 'monitoring-grafana',
        name: 'Monitoring Grafana',
        category: 'Engineering & Deployment',
        owner: 'Fajar Nugroho',
        status: 'Active',
        updated: '23 Jul 2026',
        description: 'Dashboard monitoring infrastruktur server menggunakan Prometheus sebagai sumber data.',
        version: 'v10.2.0',
        url: 'grafana.internal',
        uptime: '99.8%',
        server: 'srv-jkt-07 (Ubuntu 22.04)',
        database: 'PostgreSQL 15 + Prometheus TSDB',
        sla: '99.5% uptime guaranteed',
        documentation: 'docs.grafana.internal',
        supportContact: 'devops-team@telkomsel.internal',
    },
    {
        id: 'ticketing-system',
        name: 'Ticketing System',
        category: 'Operation',
        owner: 'Dimas Prayoga',
        status: 'Active',
        updated: '20 Jul 2026',
        description: 'Sistem tiket layanan internal untuk pelaporan dan pelacakan permintaan operasional.',
        version: 'v2.6.1',
        url: 'ticketing.internal',
        uptime: '99.3%',
        server: 'srv-jkt-02 (Ubuntu 22.04)',
        database: 'MySQL 8.0',
        sla: '99.0% uptime guaranteed',
        documentation: 'docs.ticketing.internal',
        supportContact: 'ops-support@telkomsel.internal',
    },
    {
        id: 'archive-document-store',
        name: 'Archive Document Store',
        category: 'Others',
        owner: 'Siti Rahma',
        status: 'Inactive',
        updated: '2 Jun 2026',
        description: 'Penyimpanan dokumen arsip lama, saat ini tidak aktif menunggu migrasi ke penyimpanan cloud baru.',
        version: 'v1.0.2',
        url: 'archive.internal',
        uptime: '0%',
        server: 'srv-jkt-08 (Ubuntu 20.04)',
        database: 'MySQL 5.7',
        sla: 'Tidak berlaku (nonaktif)',
        documentation: 'docs.archive.internal',
        supportContact: 'it-support@telkomsel.internal',
    },
];
