// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppHub2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811072919_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppDbContext+Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataClassification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataRetentionPolicy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("IdBackupPemilik")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdCategory")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdPembuat")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdPemilik")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdStatus")
                        .HasColumnType("uuid");

                    b.Property<string>("NamaAplikasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechnologyStack")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdBackupPemilik");

                    b.HasIndex("IdCategory");

                    b.HasIndex("IdPembuat");

                    b.HasIndex("IdPemilik");

                    b.HasIndex("IdStatus");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("AppDbContext+CategoryApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NamaCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CategoriesApp");
                });

            modelBuilder.Entity("AppDbContext+StatusApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NamaStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StatusApp");
                });

            modelBuilder.Entity("AppDbContext+User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NIK")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AppDbContext+Application", b =>
                {
                    b.HasOne("AppDbContext+User", "BackupPemilik")
                        .WithMany()
                        .HasForeignKey("IdBackupPemilik")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppDbContext+CategoryApplication", "Category")
                        .WithMany("Applications")
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppDbContext+User", "Pembuat")
                        .WithMany()
                        .HasForeignKey("IdPembuat")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppDbContext+User", "Pemilik")
                        .WithMany()
                        .HasForeignKey("IdPemilik")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppDbContext+StatusApplication", "Status")
                        .WithMany("Applications")
                        .HasForeignKey("IdStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BackupPemilik");

                    b.Navigation("Category");

                    b.Navigation("Pembuat");

                    b.Navigation("Pemilik");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("AppDbContext+CategoryApplication", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("AppDbContext+StatusApplication", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
