// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppHub2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataClassification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataRetentionPolicy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("IdBackupPemilik")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdPembuat")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdPemilik")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NamaAplikasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechnologyStack")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdBackupPemilik");

                    b.HasIndex("IdPembuat");

                    b.HasIndex("IdPemilik");

                    b.HasIndex("ServerId");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            ApplicationUrl = "https://appcatalog.internal",
                            Category = "Operations",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataClassification = "Internal",
                            DataRetentionPolicy = "5 Years",
                            DataSource = "Internal Application Database",
                            Database = "PostgreSQL",
                            Description = "Portal katalog dan akses aplikasi internal perusahaan.",
                            IdBackupPemilik = new Guid("10000000-0000-0000-0000-000000000001"),
                            IdPembuat = new Guid("10000000-0000-0000-0000-000000000001"),
                            IdPemilik = new Guid("10000000-0000-0000-0000-000000000001"),
                            LastUpdated = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NamaAplikasi = "App Catalog SSO",
                            ServerId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Status = "Active",
                            TechnologyStack = ".NET, React, PostgreSQL",
                            Version = "2.5.0"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            ApplicationUrl = "https://finance.internal",
                            Category = "Budgeting & Finance",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataClassification = "Confidential",
                            DataRetentionPolicy = "7 Years",
                            DataSource = "Finance Database",
                            Database = "PostgreSQL",
                            Description = "Aplikasi internal untuk pengelolaan keuangan dan budgeting.",
                            IdBackupPemilik = new Guid("10000000-0000-0000-0000-000000000001"),
                            IdPembuat = new Guid("10000000-0000-0000-0000-000000000001"),
                            IdPemilik = new Guid("10000000-0000-0000-0000-000000000001"),
                            LastUpdated = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            NamaAplikasi = "Finance Management System",
                            ServerId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Status = "Active",
                            TechnologyStack = ".NET, Angular, PostgreSQL",
                            Version = "3.2.1"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            ApplicationUrl = "https://network-monitor.internal",
                            Category = "Operations",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataClassification = "Internal",
                            DataRetentionPolicy = "1 Year",
                            DataSource = "Network Monitoring API",
                            Database = "PostgreSQL",
                            Description = "Monitoring kondisi jaringan dan layanan internal.",
                            IdBackupPemilik = new Guid("10000000-0000-0000-0000-000000000001"),
                            IdPembuat = new Guid("10000000-0000-0000-0000-000000000001"),
                            IdPemilik = new Guid("10000000-0000-0000-0000-000000000001"),
                            LastUpdated = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            NamaAplikasi = "Network Monitoring",
                            ServerId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Status = "Active",
                            TechnologyStack = ".NET, React, Prometheus",
                            Version = "4.1.0"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            ApplicationUrl = "https://security.internal",
                            Category = "Security",
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataClassification = "Restricted",
                            DataRetentionPolicy = "3 Years",
                            DataSource = "Security Event Logs",
                            Database = "PostgreSQL",
                            Description = "Dashboard monitoring event dan security internal.",
                            IdBackupPemilik = new Guid("10000000-0000-0000-0000-000000000001"),
                            IdPembuat = new Guid("10000000-0000-0000-0000-000000000001"),
                            IdPemilik = new Guid("10000000-0000-0000-0000-000000000001"),
                            LastUpdated = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            NamaAplikasi = "Security Dashboard",
                            ServerId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Status = "Active",
                            TechnologyStack = ".NET, React, Elasticsearch",
                            Version = "2.8.0"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            ApplicationUrl = "https://deployment.internal",
                            Category = "Engineering & Deployment",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataClassification = "Internal",
                            DataRetentionPolicy = "1 Year",
                            DataSource = "CI/CD Platform",
                            Database = "PostgreSQL",
                            Description = "Aplikasi internal untuk pengelolaan deployment.",
                            IdBackupPemilik = new Guid("10000000-0000-0000-0000-000000000001"),
                            IdPembuat = new Guid("10000000-0000-0000-0000-000000000001"),
                            IdPemilik = new Guid("10000000-0000-0000-0000-000000000001"),
                            LastUpdated = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            NamaAplikasi = "Deployment Manager",
                            ServerId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Status = "Active",
                            TechnologyStack = ".NET, Vue, PostgreSQL",
                            Version = "1.9.4"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            ApplicationUrl = "https://inventory.internal",
                            Category = "Operations",
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataClassification = "Internal",
                            DataRetentionPolicy = "3 Years",
                            DataSource = "Inventory Database",
                            Database = "MySQL",
                            Description = "Aplikasi pengelolaan inventory internal.",
                            IdBackupPemilik = new Guid("10000000-0000-0000-0000-000000000001"),
                            IdPembuat = new Guid("10000000-0000-0000-0000-000000000001"),
                            IdPemilik = new Guid("10000000-0000-0000-0000-000000000001"),
                            LastUpdated = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            NamaAplikasi = "Inventory System",
                            ServerId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Status = "Inactive",
                            TechnologyStack = "Laravel, MySQL, Bootstrap",
                            Version = "1.4.2"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            ApplicationUrl = "https://budget.internal",
                            Category = "Budgeting & Finance",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataClassification = "Confidential",
                            DataRetentionPolicy = "7 Years",
                            DataSource = "Finance Database",
                            Database = "PostgreSQL",
                            Description = "Perencanaan dan monitoring budget internal.",
                            IdBackupPemilik = new Guid("10000000-0000-0000-0000-000000000001"),
                            IdPembuat = new Guid("10000000-0000-0000-0000-000000000001"),
                            IdPemilik = new Guid("10000000-0000-0000-0000-000000000001"),
                            NamaAplikasi = "Budget Planning",
                            ServerId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Status = "Pending",
                            TechnologyStack = ".NET, React, PostgreSQL",
                            Version = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            ApplicationUrl = "https://employee.internal",
                            Category = "Others",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataClassification = "Internal",
                            DataRetentionPolicy = "5 Years",
                            DataSource = "Employee Database",
                            Database = "PostgreSQL",
                            Description = "Portal layanan internal untuk employee.",
                            IdBackupPemilik = new Guid("10000000-0000-0000-0000-000000000001"),
                            IdPembuat = new Guid("10000000-0000-0000-0000-000000000001"),
                            IdPemilik = new Guid("10000000-0000-0000-0000-000000000001"),
                            LastUpdated = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            NamaAplikasi = "Employee Portal",
                            ServerId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Status = "Active",
                            TechnologyStack = ".NET, React, PostgreSQL",
                            Version = "3.0.5"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            ApplicationUrl = "https://gateway.internal",
                            Category = "Engineering & Deployment",
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataClassification = "Internal",
                            DataRetentionPolicy = "1 Year",
                            DataSource = "Internal APIs",
                            Database = "PostgreSQL",
                            Description = "Gateway untuk integrasi berbagai API internal.",
                            IdBackupPemilik = new Guid("10000000-0000-0000-0000-000000000001"),
                            IdPembuat = new Guid("10000000-0000-0000-0000-000000000001"),
                            IdPemilik = new Guid("10000000-0000-0000-0000-000000000001"),
                            LastUpdated = new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            NamaAplikasi = "API Gateway",
                            ServerId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Status = "Active",
                            TechnologyStack = ".NET, Redis, PostgreSQL",
                            Version = "5.3.0"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            ApplicationUrl = "https://logs.internal",
                            Category = "Security",
                            CreatedAt = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataClassification = "Restricted",
                            DataRetentionPolicy = "2 Years",
                            DataSource = "Application Logs",
                            Database = "Elasticsearch",
                            Description = "Centralized log management untuk aplikasi internal.",
                            IdBackupPemilik = new Guid("10000000-0000-0000-0000-000000000001"),
                            IdPembuat = new Guid("10000000-0000-0000-0000-000000000001"),
                            IdPemilik = new Guid("10000000-0000-0000-0000-000000000001"),
                            NamaAplikasi = "Log Management",
                            ServerId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Status = "Pending",
                            TechnologyStack = ".NET, Elasticsearch, Kibana",
                            Version = "1.1.0"
                        });
                });

            modelBuilder.Entity("backend.Models.Complaint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("CategoryMasalah");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LdapUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("UsernameLDAP");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Regional")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Submitted");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("Complaints");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            ApplicationId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Category = "Reviewer User",
                            CreatedAt = new DateTime(2026, 8, 21, 2, 0, 0, 0, DateTimeKind.Utc),
                            Description = "User tidak dapat membuka menu reviewer pada aplikasi.",
                            Email = "budi@example.com",
                            FullName = "Budi Santoso",
                            IssueType = "User Management",
                            LdapUsername = "budi",
                            Phone = "081234567891",
                            Regional = "HQ",
                            ResolutionNote = "Akses reviewer telah ditambahkan oleh administrator.",
                            ResolvedAt = new DateTime(2026, 8, 21, 5, 30, 0, 0, DateTimeKind.Utc),
                            Role = "Read Only",
                            Status = "Resolved",
                            UpdatedAt = new DateTime(2026, 8, 21, 5, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            ApplicationId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Category = "Reviewer User",
                            CreatedAt = new DateTime(2026, 8, 22, 3, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Role pengguna tidak sesuai dengan jabatan yang dimiliki.",
                            Email = "siti@example.com",
                            FullName = "Siti Rahma",
                            IssueType = "User Management",
                            LdapUsername = "siti",
                            Phone = "081234567892",
                            Regional = "RI SUMBAGUT",
                            ResolutionNote = "Sedang dilakukan pengecekan role dan department pengguna.",
                            Role = "Read And Write",
                            Status = "Checking",
                            UpdatedAt = new DateTime(2026, 8, 22, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            ApplicationId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Category = "Data Not Synchronize",
                            CreatedAt = new DateTime(2026, 8, 23, 1, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Data transaksi terbaru belum muncul pada dashboard finance.",
                            Email = "rina@example.com",
                            FullName = "Rina Wijaya",
                            IssueType = "Data Not Synchronize",
                            Phone = "081234567894",
                            Regional = "HQ",
                            ResolutionNote = "Tim sedang memeriksa proses sinkronisasi database.",
                            Status = "Checking",
                            UpdatedAt = new DateTime(2026, 8, 23, 4, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            ApplicationId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Category = "KPI",
                            CreatedAt = new DateTime(2026, 8, 24, 2, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Halaman KPI membutuhkan waktu cukup lama untuk ditampilkan.",
                            Email = "admin@example.com",
                            FullName = "Administrator",
                            IssueType = "Performance",
                            Phone = "081234567890",
                            Regional = "HQ",
                            Status = "Submitted"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            ApplicationId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Category = "RH Visit",
                            CreatedAt = new DateTime(2026, 8, 25, 1, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dashboard network monitoring sering mengalami loading lama.",
                            Email = "andika@example.com",
                            FullName = "Andika Putra",
                            IssueType = "Performance",
                            Phone = "081234567893",
                            Regional = "R4 WEST JAVA",
                            Status = "Submitted"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000006"),
                            ApplicationId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Category = "Ticketing Handling",
                            CreatedAt = new DateTime(2026, 8, 25, 4, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tombol pembuatan ticket tidak merespons ketika diklik.",
                            Email = "andika@example.com",
                            FullName = "Andika Putra",
                            IssueType = "Aplication Error",
                            Phone = "081234567893",
                            Regional = "R6 EAST JAVA",
                            ResolutionNote = "Masalah pada endpoint ticketing telah diperbaiki.",
                            ResolvedAt = new DateTime(2026, 8, 26, 2, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Resolved",
                            UpdatedAt = new DateTime(2026, 8, 26, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000007"),
                            ApplicationId = new Guid("20000000-0000-0000-0000-000000000004"),
                            Category = "Ticketing Handling",
                            CreatedAt = new DateTime(2026, 8, 26, 3, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Notifikasi security alert tidak dapat dibuka.",
                            Email = "rina@example.com",
                            FullName = "Rina Wijaya",
                            IssueType = "Aplication Error",
                            Phone = "081234567894",
                            Regional = "HQ",
                            ResolutionNote = "Complaint ditutup setelah perbaikan dan konfirmasi pengguna.",
                            ResolvedAt = new DateTime(2026, 8, 27, 2, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Closed",
                            UpdatedAt = new DateTime(2026, 8, 27, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000008"),
                            ApplicationId = new Guid("20000000-0000-0000-0000-000000000005"),
                            Category = "Data Not Synchronize",
                            CreatedAt = new DateTime(2026, 8, 27, 5, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Riwayat deployment terbaru belum tampil pada dashboard.",
                            Email = "budi@example.com",
                            FullName = "Budi Santoso",
                            IssueType = "Data Not Synchronize",
                            Phone = "081234567891",
                            Regional = "R4 WEST JAVA",
                            ResolutionNote = "Sedang dilakukan pengecekan deployment service.",
                            Status = "Checking",
                            UpdatedAt = new DateTime(2026, 8, 28, 1, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000009"),
                            ApplicationId = new Guid("20000000-0000-0000-0000-000000000006"),
                            Category = "Data Not Synchronize",
                            CreatedAt = new DateTime(2026, 8, 28, 3, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Jumlah stok pada dashboard berbeda dengan database.",
                            Email = "siti@example.com",
                            FullName = "Siti Rahma",
                            IssueType = "Data Not Synchronize",
                            Phone = "081234567892",
                            Regional = "R6 EAST JAVA",
                            ResolutionNote = "Proses sinkronisasi stok telah dijalankan ulang.",
                            ResolvedAt = new DateTime(2026, 8, 29, 2, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Resolved",
                            UpdatedAt = new DateTime(2026, 8, 29, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000010"),
                            ApplicationId = new Guid("20000000-0000-0000-0000-000000000007"),
                            Category = "KPI",
                            CreatedAt = new DateTime(2026, 8, 29, 4, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Proses menampilkan laporan anggaran berjalan lambat.",
                            Email = "admin@example.com",
                            FullName = "Administrator",
                            IssueType = "Performance",
                            Phone = "081234567890",
                            Regional = "HQ",
                            Status = "Submitted"
                        });
                });

            modelBuilder.Entity("backend.Models.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlertLevel")
                        .HasColumnType("text");

                    b.Property<double>("Availability")
                        .HasColumnType("double precision");

                    b.Property<double>("CpuUsage")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double>("DiskUsage")
                        .HasColumnType("double precision");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastChecked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("MemoryUsage")
                        .HasColumnType("double precision");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Servers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            AlertLevel = "Info",
                            Availability = 99.900000000000006,
                            CpuUsage = 32.0,
                            Description = "Main production server untuk aplikasi internal",
                            DiskUsage = 55.0,
                            IpAddress = "192.168.1.10",
                            IsCritical = false,
                            LastChecked = new DateTime(2026, 8, 20, 8, 0, 0, 0, DateTimeKind.Utc),
                            MemoryUsage = 48.0,
                            Region = "Jakarta",
                            ResponseTimeMs = 85,
                            ServerName = "Production Server Jakarta",
                            Status = "Online"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            AlertLevel = "Warning",
                            Availability = 98.700000000000003,
                            CpuUsage = 72.0,
                            Description = "Server untuk aplikasi finance dan operation",
                            DiskUsage = 68.0,
                            IpAddress = "192.168.1.20",
                            IsCritical = false,
                            LastChecked = new DateTime(2026, 8, 20, 8, 0, 0, 0, DateTimeKind.Utc),
                            MemoryUsage = 78.0,
                            Region = "Jakarta",
                            ResponseTimeMs = 230,
                            ServerName = "Finance & Operation Server",
                            Status = "Warning"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            AlertLevel = "Critical",
                            Availability = 94.5,
                            CpuUsage = 94.0,
                            Description = "Server network dan security dengan resource tinggi",
                            DiskUsage = 84.0,
                            IpAddress = "192.168.1.30",
                            IsCritical = true,
                            LastChecked = new DateTime(2026, 8, 20, 8, 0, 0, 0, DateTimeKind.Utc),
                            MemoryUsage = 91.0,
                            Region = "Surabaya",
                            ResponseTimeMs = 760,
                            ServerName = "Security & Network Server",
                            Status = "Critical"
                        });
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlasanPengajuan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LevelAccess")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NIK")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telp")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            AlasanPengajuan = "Administrator aplikasi monitoring internal",
                            Department = "Others",
                            Email = "admin@example.com",
                            LevelAccess = "Admin",
                            NIK = "1234567890",
                            Nama = "Administrator",
                            Password = "admin123",
                            Telp = "081234567890",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            AlasanPengajuan = "Akses monitoring Finance Management System",
                            ApplicationId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Department = "Budgeting & Finance",
                            Email = "budi@example.com",
                            LevelAccess = "Read Only",
                            NIK = "1234567891",
                            Nama = "Budi Santoso",
                            Password = "user123",
                            Telp = "081234567891",
                            Username = "budi"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            AlasanPengajuan = "Akses pengelolaan App Catalog SSO",
                            ApplicationId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Department = "Operations",
                            Email = "siti@example.com",
                            LevelAccess = "Read And Write",
                            NIK = "1234567892",
                            Nama = "Siti Rahma",
                            Password = "user123",
                            Telp = "081234567892",
                            Username = "siti"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            AlasanPengajuan = "Akses monitoring Network Monitoring",
                            ApplicationId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Department = "Operations",
                            Email = "andika@example.com",
                            LevelAccess = "Read And Write",
                            NIK = "1234567893",
                            Nama = "Andika Putra",
                            Password = "user123",
                            Telp = "081234567893",
                            Username = "andika"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            AlasanPengajuan = "Akses monitoring Security Dashboard",
                            ApplicationId = new Guid("20000000-0000-0000-0000-000000000004"),
                            Department = "Security",
                            Email = "rina@example.com",
                            LevelAccess = "Read Only",
                            NIK = "1234567894",
                            Nama = "Rina Wijaya",
                            Password = "user123",
                            Telp = "081234567894",
                            Username = "rina"
                        });
                });

            modelBuilder.Entity("backend.Models.UserApplicationAccess", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GrantedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("UserId", "ApplicationId");

                    b.HasIndex("ApplicationId");

                    b.ToTable("UserApplicationAccesses");
                });

            modelBuilder.Entity("backend.Models.Application", b =>
                {
                    b.HasOne("backend.Models.User", "BackupPemilik")
                        .WithMany()
                        .HasForeignKey("IdBackupPemilik")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.User", "Pembuat")
                        .WithMany()
                        .HasForeignKey("IdPembuat")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "Pemilik")
                        .WithMany()
                        .HasForeignKey("IdPemilik")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.Server", "Server")
                        .WithMany("Applications")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BackupPemilik");

                    b.Navigation("Pembuat");

                    b.Navigation("Pemilik");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("backend.Models.Complaint", b =>
                {
                    b.HasOne("backend.Models.Application", "Application")
                        .WithMany("Complaints")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.HasOne("backend.Models.Application", "Application")
                        .WithMany("Users")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Application");
                });

            modelBuilder.Entity("backend.Models.UserApplicationAccess", b =>
                {
                    b.HasOne("backend.Models.Application", "Application")
                        .WithMany("UserAccesses")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("ApplicationAccesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Application", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("UserAccesses");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("backend.Models.Server", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("ApplicationAccesses");
                });
#pragma warning restore 612, 618
        }
    }
}
